server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_user
    username: postgres
    password: 159753
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

## Actuator ##
management:
  endpoints:
    web:
      exposure:
        include: health,info

## OpenApi Settings ##
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/docs/swagger-ui.html"

openapi:
  app:
    title: "User API"
    description: "To Learn This Project Authentication"
    version: 1.0
    contact : "Contact Support"
    email: "ozdenizm6@gmail.com"
    licence: "Ozdeniz 1.0"
    url: "https://baranozdeniz.com"